import type { Category, Product } from "@/types/database";

export const CATEGORIES: Category[] = [
  { id: "cat-1", name: "Bolos", slug: "bolos", display_order: 1 },
  { id: "cat-2", name: "Sobremesa", slug: "sobremesa", display_order: 2 },
  { id: "cat-3", name: "Gelinhos", slug: "gelinhos", display_order: 3 },
];

export const PRODUCTS: Product[] = [
  // ═══════════════════════ SOBREMESAS ═══════════════════════
  { id: "s-1", category_id: "cat-2", name: "Bolo no Pote - Ninho com Morango", description: "Camadas generosas de bolo fofinho com recheio cremoso de Ninho e morangos frescos.", price: 10.00, image_url: null, is_available: true, display_order: 1, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-2", category_id: "cat-2", name: "Bolo no Pote - Ninho com Abacaxi", description: "Massa leve intercalada com creme de Ninho e pedaços suculentos de abacaxi.", price: 10.00, image_url: null, is_available: true, display_order: 2, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-3", category_id: "cat-2", name: "Bolo no Pote - Ninho com Nutella", description: "Combinação perfeita de creme de Ninho com a autêntica Nutella em camadas no pote.", price: 10.00, image_url: null, is_available: true, display_order: 3, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-4", category_id: "cat-2", name: "Bolo no Pote - Prestígio", description: "Bolo de chocolate artesanal com recheio cremoso de prestígio e coco ralado.", price: 10.00, image_url: null, is_available: true, display_order: 4, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-5", category_id: "cat-2", name: "Bolo no Pote - Brigadeiro", description: "Massa de chocolate recheada com brigadeiro gourmet tradicional e granulado.", price: 10.00, image_url: null, is_available: true, display_order: 5, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-6", category_id: "cat-2", name: "Bolo no Pote - Choconinho", description: "O melhor dos dois mundos: camadas alternadas de recheio de Ninho e chocolate.", price: 10.00, image_url: null, is_available: true, display_order: 6, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-7", category_id: "cat-2", name: "Bolo no Pote - Morango Cravejado", description: "Bolo no pote especial com camada extra e abundante de morangos e cobertura.", price: 12.50, image_url: null, is_available: true, display_order: 7, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-8", category_id: "cat-2", name: "Copo da Felicidade", description: "Combinação irresistível de recheios cremosos, acompanhamentos e bombons no copo.", price: 17.50, image_url: null, is_available: true, display_order: 8, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-9", category_id: "cat-2", name: "Mini Pavê", description: "Sobremesa clássica e cremosa servida em porção individual na medida certa.", price: 7.50, image_url: null, is_available: true, display_order: 9, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-10", category_id: "cat-2", name: "Cupcake - Brigadeiro", description: "Bolinhos macios com cobertura bem generosa de brigadeiro gourmet.", price: 10.00, image_url: null, is_available: true, display_order: 10, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-11", category_id: "cat-2", name: "Cupcake - Cenoura com Brigadeiro", description: "O clássico bolo de cenoura em versão cupcake com cobertura de brigadeiro.", price: 10.00, image_url: null, is_available: true, display_order: 11, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-12", category_id: "cat-2", name: "Bolo Gelado - Prestígio", description: "Bolo de chocolate bem molhadinho, recheado com coco e coberto com calda gelada.", price: 10.00, image_url: null, is_available: true, display_order: 12, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-13", category_id: "cat-2", name: "Bolo Gelado - Coco", description: "Bolo de coco ultra molhado embrulhado e servido bem gelado.", price: 10.00, image_url: null, is_available: true, display_order: 13, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-14", category_id: "cat-2", name: "Brownie - Tradicional", description: "Brownie de chocolate com casquinha crocante por fora e massa densa e macia por dentro.", price: 8.50, image_url: null, is_available: true, display_order: 14, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-15", category_id: "cat-2", name: "Brownie - Ninho com KitKat", description: "Pedaço de brownie coberto com creme de Ninho e pedaços crocantes de KitKat.", price: 14.00, image_url: null, is_available: true, display_order: 15, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-16", category_id: "cat-2", name: "Brownie - Ninho com Kinder Bueno", description: "Brownie artesanal com cobertura de Ninho e bombom Kinder Bueno.", price: 14.00, image_url: null, is_available: true, display_order: 16, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-17", category_id: "cat-2", name: "Brownie - Ninho com Morango", description: "Brownie macio coberto com creme de Ninho suave e morangos frescos picados.", price: 14.00, image_url: null, is_available: true, display_order: 17, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "s-18", category_id: "cat-2", name: "Brownie - Ninho com Nutella", description: "Combinação campeã de brownie de chocolate, creme de Ninho e bastante Nutella.", price: 14.00, image_url: null, is_available: true, display_order: 18, brand: "", isCustomWeight: false, controlarEstoque: false },
  // ═══════════════════════ BOLOS (sob encomenda, sem controle de estoque) ═══════════════════════
  { id: "b-1", category_id: "cat-1", name: "Bolo de Chocolate", description: "Bolo artesanal de chocolate com recheio derretido de ninho e nutella.", price: 89.90, image_url: "/imagens/BoloChocolate.webp", is_available: true, display_order: 1, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "b-3", category_id: "cat-1", name: "Bolo de Cenoura com Brigadeiro", description: "Fofinho de cenoura com cobertura de brigadeiro belga 70% cacau.", price: 79.90, image_url: "/imagens/BoloChocolateCenoura.webp", is_available: true, display_order: 2, brand: "", isCustomWeight: false, controlarEstoque: false },
  { id: "b-4", category_id: "cat-1", name: "Bolo Ninho com Morango", description: "Pão de ló fofinho recheado com creme aveludado de Leite Ninho e morangos frescos selecionados.", price: 100.00, image_url: null, is_available: true, display_order: 3, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-5", category_id: "cat-1", name: "Bolo Ninho com Abacaxi", description: "Massa leve recheada com suave creme de Leite Ninho e pedaços suculentos de abacaxi cozido.", price: 90.00, image_url: null, is_available: true, display_order: 4, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-6", category_id: "cat-1", name: "Bolo Ninho com Nutella", description: "Combinação irresistível de recheio cremoso de Leite Ninho com generosa camada de Nutella pura.", price: 110.00, image_url: null, is_available: true, display_order: 5, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-7", category_id: "cat-1", name: "Bolo Mousse de Limão", description: "Bolo leve com recheio de mousse refrescante de limão e toque sutil de raspas cítricas.", price: 90.00, image_url: null, is_available: true, display_order: 6, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-8", category_id: "cat-1", name: "Bolo Mousse de Maracujá", description: "Recheio aerado e cremoso de mousse de maracujá com o equilíbrio perfeito entre o doce e o azedinho.", price: 90.00, image_url: null, is_available: true, display_order: 7, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-9", category_id: "cat-1", name: "Bolo Mousse de Morango com pedaços de Morango", description: "Mousse leve de morango recheada com pedaços fartos de morangos frescos.", price: 95.00, image_url: null, is_available: true, display_order: 8, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-10", category_id: "cat-1", name: "Bolo de Abacaxi com creme belga", description: "Clássico e delicado, recheado com o tradicional e aveludado creme belga e pedaços de abacaxi.", price: 85.00, image_url: null, is_available: true, display_order: 9, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-11", category_id: "cat-1", name: "Bolo Creme Belga com Morango", description: "Massa macia recheada com creme belga artesanal e morangos frescos fatiados.", price: 95.00, image_url: null, is_available: true, display_order: 10, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-12", category_id: "cat-1", name: "Bolo Prestígio", description: "Bolo de chocolate com recheio cremoso de coco ralado e cobertura rica de brigadeiro.", price: 100.00, image_url: null, is_available: true, display_order: 11, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-13", category_id: "cat-1", name: "Bolo Brigadeiro", description: "O queridinho das festas, recheado e coberto com brigadeiro gourmet cremoso e granulados.", price: 100.00, image_url: null, is_available: true, display_order: 12, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-14", category_id: "cat-1", name: "Bolo Mousse de Chocolate", description: "Textura extremamente aveludada com mousse de chocolate nobre e sabor intenso.", price: 120.00, image_url: null, is_available: true, display_order: 13, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-15", category_id: "cat-1", name: "Bolo Quatro Leites com Abacaxi", description: "Recheio especial de quatro leites combinado com a leveza e doçura do abacaxi cozido.", price: 95.00, image_url: null, is_available: true, display_order: 14, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-16", category_id: "cat-1", name: "Bolo Brigadeiro de Ninho com Geleia de Morango", description: "Delicioso brigadeiro cremoso de Leite Ninho combinado com geleia artesanal de morango.", price: 100.00, image_url: null, is_available: true, display_order: 15, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-17", category_id: "cat-1", name: "Bolo Doce de Leite com Abacaxi", description: "Combinação tradicional de doce de leite cremoso com pedaços macios de abacaxi.", price: 90.00, image_url: null, is_available: true, display_order: 16, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-18", category_id: "cat-1", name: "Bolo Dois Amores", description: "O encontro perfeito entre o recheio cremoso de brigadeiro tradicional e brigadeiro branco.", price: 100.00, image_url: null, is_available: true, display_order: 17, brand: "", isCustomWeight: true, controlarEstoque: false },
  { id: "b-19", category_id: "cat-1", name: "Bolo Olho de Sogra", description: "Combinação clássica e marcante de recheio de doce de leite cremoso, beijinho de coco e ameixas fatiadas.", price: 95.00, image_url: null, is_available: true, display_order: 18, brand: "", isCustomWeight: true, controlarEstoque: false },

  // ═══════════════════════ GELINHOS — R$ 8,50 (Premium) ═══════════════════════
  { id: "g-1", category_id: "cat-3", name: "Gelinho Nutella", description: "Gelinho super cremoso preparado com base especial e recheio generoso de Nutella pura.", price: 8.50, precoCustoInicial: 3.40, image_url: null, is_available: true, display_order: 1, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-2", category_id: "cat-3", name: "Gelinho Doce de Leite", description: "Gelinho gourmet extremamente cremoso com doce de leite artesanal encorpado.", price: 8.50, precoCustoInicial: 3.20, image_url: null, is_available: true, display_order: 2, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-3", category_id: "cat-3", name: "Gelinho Maracujá com Nutella", description: "A combinação perfeita entre o azedinho da polpa de maracujá e a cremosidade da Nutella.", price: 8.50, precoCustoInicial: 3.50, image_url: null, is_available: true, display_order: 3, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-4", category_id: "cat-3", name: "Gelinho Morango com Chocolate Branco", description: "Pedaços e calda de morango artesanal envolvidos em uma base cremosa de chocolate branco.", price: 8.50, precoCustoInicial: 3.30, image_url: null, is_available: true, display_order: 4, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-5", category_id: "cat-3", name: "Gelinho Limão com Chocolate Branco", description: "Toque cítrico de limão fresco combinado com a suavidade do chocolate branco cremoso.", price: 8.50, precoCustoInicial: 3.10, image_url: null, is_available: true, display_order: 5, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },

  // ═══════════════════════ GELINHOS — R$ 8,00 ═══════════════════════
  { id: "g-6", category_id: "cat-3", name: "Gelinho Pudim", description: "Gelinho gourmet inspirado no clássico pudim de leite condensado com calda caseira de caramelo.", price: 8.00, precoCustoInicial: 3.00, image_url: null, is_available: true, display_order: 6, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },

  // ═══════════════════════ GELINHOS — R$ 7,50 (Recheados & Clássicos) ═══════════════════════
  { id: "g-7", category_id: "cat-3", name: "Gelinho Limão com Chocolate ao Leite", description: "Creme refrescante de limão acompanhado com uma camada cremosa de chocolate ao leite.", price: 7.50, precoCustoInicial: 2.90, image_url: null, is_available: true, display_order: 7, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-8", category_id: "cat-3", name: "Gelinho Coco com Abacaxi", description: "Deliciosa combinação tropical de coco ralado com pedaços e calda artesanal de abacaxi.", price: 7.50, precoCustoInicial: 2.70, image_url: null, is_available: true, display_order: 8, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-9", category_id: "cat-3", name: "Gelinho Morango com Nutella", description: "Polpa natural de morango combinado com bastante Nutella.", price: 7.50, precoCustoInicial: 3.20, image_url: null, is_available: true, display_order: 9, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-10", category_id: "cat-3", name: "Gelinho Ninho com Nutella", description: "A clássica e irresistível combinação de Leite Ninho cremoso com recheio abundante de Nutella.", price: 7.50, precoCustoInicial: 3.20, image_url: null, is_available: true, display_order: 10, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-11", category_id: "cat-3", name: "Gelinho Prestígio", description: "Base cremosa de coco artesanal com generosa camada de chocolate ao leite.", price: 7.50, precoCustoInicial: 2.80, image_url: null, is_available: true, display_order: 11, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-12", category_id: "cat-3", name: "Gelinho Sensação", description: "Mistura perfeita de morango cremoso com pedaços de chocolate ao leite.", price: 7.50, precoCustoInicial: 2.90, image_url: null, is_available: true, display_order: 12, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },

  // ═══════════════════════ GELINHOS — R$ 6,50 (Tradicional Gourmet) ═══════════════════════
  { id: "g-13", category_id: "cat-3", name: "Gelinho Ninho com Morango", description: "Creme de Leite Ninho combinado com geléia artesanal de morango fresco.", price: 6.50, precoCustoInicial: 2.60, image_url: null, is_available: true, display_order: 13, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-14", category_id: "cat-3", name: "Gelinho Ninho com Maracujá", description: "O equilíbrio suave do Leite Ninho cremoso com polpa natural de maracujá.", price: 6.50, precoCustoInicial: 2.50, image_url: null, is_available: true, display_order: 14, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-15", category_id: "cat-3", name: "Gelinho Maracujá", description: "Gelinho ultra cremoso preparado com a pura polpa natural do maracujá.", price: 6.50, precoCustoInicial: 2.40, image_url: null, is_available: true, display_order: 15, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-16", category_id: "cat-3", name: "Gelinho Abacaxi", description: "Refrescante e cremoso, feito com a fruta fresca de abacaxi.", price: 6.50, precoCustoInicial: 2.30, image_url: null, is_available: true, display_order: 16, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-17", category_id: "cat-3", name: "Gelinho Coco", description: "Sabor clássico e aveludado com coco ralado natural e base cremosa.", price: 6.50, precoCustoInicial: 2.20, image_url: null, is_available: true, display_order: 17, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-18", category_id: "cat-3", name: "Gelinho Coco Queimado", description: "Sabor marcante de coco queimado artesanalmente com toque cremoso.", price: 6.50, precoCustoInicial: 2.40, image_url: null, is_available: true, display_order: 18, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
  { id: "g-19", category_id: "cat-3", name: "Gelinho Paçoca", description: "Creme saboroso preparado com paçoca de amendoim de alta qualidade.", price: 6.50, precoCustoInicial: 2.50, image_url: null, is_available: true, display_order: 19, brand: "", isCustomWeight: false, controlarEstoque: true, estoque: 10, estoqueMinimo: 5, estoqueCritico: 2 },
];

export const CATEGORY_EMOJI: Record<string, string> = {
  "cat-1": "🎂",
  "cat-2": "🍮",
  "cat-3": "🧊",
};

export const DEFAULT_CATEGORY_EMOJI = "🍰";

export function getCategoryEmoji(categoryId: string, categoryName?: string): string {
  const byId = CATEGORY_EMOJI[categoryId];
  if (byId) return byId;
  const norm = (categoryName ?? "").toLowerCase();
  if (norm.includes("bolo")) return "🎂";
  if (norm.includes("sobremesa") || norm.includes("doce")) return "🍮";
  if (norm.includes("gelinho")) return "🧊";
  if (norm.includes("salgado")) return "🥨";
  if (norm.includes("torta")) return "🥧";
  return DEFAULT_CATEGORY_EMOJI;
}
