export interface SeedStockItem {
  id: string;
  name: string;
  category: string;
  min: number;
  unit: string;
}

export const SEED_STOCK: SeedStockItem[] = [
  // ── Uso Interno ──
  { id: "si-01", name: "Açúcar", category: "Uso Interno", min: 10, unit: "kg" },
  { id: "si-02", name: "Farinha de Trigo", category: "Uso Interno", min: 10, unit: "kg" },
  { id: "si-03", name: "Amido de Milho", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-04", name: "Fermento em Pó", category: "Uso Interno", min: 3, unit: "g" },
  { id: "si-05", name: "Chocolate em Pó 50%", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-06", name: "Óleo", category: "Uso Interno", min: 6, unit: "L" },
  { id: "si-07", name: "Ovos", category: "Uso Interno", min: 30, unit: "un" },
  { id: "si-08", name: "Emulsificante", category: "Uso Interno", min: 2, unit: "g" },
  { id: "si-09", name: "Coco Ralado", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-10", name: "Leite de Coco", category: "Uso Interno", min: 10, unit: "lata" },
  { id: "si-11", name: "Leite Condensado", category: "Uso Interno", min: 20, unit: "lata" },
  { id: "si-12", name: "Leite em Pó", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-13", name: "Leite Integral", category: "Uso Interno", min: 10, unit: "L" },
  { id: "si-14", name: "Creme de Leite", category: "Uso Interno", min: 20, unit: "caixa" },
  { id: "si-15", name: "Baunilha", category: "Uso Interno", min: 3, unit: "ml" },
  { id: "si-16", name: "Manteiga", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-17", name: "Margarina", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-18", name: "Chocolate Ao Leite Barra", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-19", name: "Chocolate Meio Amargo Barra", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-20", name: "Chocolate Branco Barra", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-21", name: "Chocolate Blend", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-22", name: "Cobertura ao Leite", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-23", name: "Cobertura Branco", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-24", name: "Suspiro", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-25", name: "Fubá", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-26", name: "Goiabada", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-27", name: "Bicarbonato de Sódio", category: "Uso Interno", min: 2, unit: "g" },
  { id: "si-28", name: "Sal", category: "Uso Interno", min: 3, unit: "g" },
  { id: "si-29", name: "Creme de Avelã", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-30", name: "Suco em Pó Morango", category: "Uso Interno", min: 5, unit: "pct" },
  { id: "si-31", name: "Suco em Pó Abacaxi", category: "Uso Interno", min: 3, unit: "pct" },
  { id: "si-32", name: "Suco em Pó Maracujá", category: "Uso Interno", min: 3, unit: "pct" },
  { id: "si-33", name: "Suco em Pó Limão", category: "Uso Interno", min: 3, unit: "pct" },
  { id: "si-34", name: "Nesquik", category: "Uso Interno", min: 3, unit: "pct" },
  { id: "si-35", name: "Corante em Gel", category: "Uso Interno", min: 5, unit: "un" },
  { id: "si-36", name: "Pó Pérola", category: "Uso Interno", min: 2, unit: "g" },
  { id: "si-37", name: "Liga Neutra", category: "Uso Interno", min: 3, unit: "g" },
  { id: "si-38", name: "Amendoim Moído", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-39", name: "Chantilly", category: "Uso Interno", min: 5, unit: "L" },
  { id: "si-40", name: "Morango", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-41", name: "Cereja", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-42", name: "Ameixa", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-43", name: "Abacaxi", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-44", name: "Maracujá", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-45", name: "Limão", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-46", name: "Uva", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-47", name: "Kiwi", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-48", name: "Laranja", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-49", name: "Maçã", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-50", name: "Mamão", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-51", name: "Manga", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-52", name: "Coco Fresco", category: "Uso Interno", min: 3, unit: "un" },
  { id: "si-53", name: "Confeitos e Coberturas Diversos", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-54", name: "Confeito Pérola", category: "Uso Interno", min: 2, unit: "g" },
  { id: "si-55", name: "Confeito Dourado", category: "Uso Interno", min: 1, unit: "g" },
  { id: "si-56", name: "Granulado Colorido", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-57", name: "Granulé ao Leite", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-58", name: "Confeito Branco", category: "Uso Interno", min: 1, unit: "g" },
  { id: "si-59", name: "Chocolate KitKat", category: "Uso Interno", min: 5, unit: "un" },
  { id: "si-60", name: "Chocolate Kinder Bueno", category: "Uso Interno", min: 5, unit: "un" },
  { id: "si-61", name: "Chocolate Ouro Branco", category: "Uso Interno", min: 5, unit: "un" },
  { id: "si-62", name: "Chocolate Sonho de Valsa", category: "Uso Interno", min: 5, unit: "un" },
  { id: "si-63", name: "Biscoito de Maizena", category: "Uso Interno", min: 5, unit: "pct" },

  // ── Embalagens ──
  { id: "si-64", name: "Saquinho 5x24", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-65", name: "Saquinho 4x24", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-66", name: "Colher Descartável", category: "Embalagens", min: 100, unit: "un" },
  { id: "si-67", name: "Sacolinha Plástica 25x35", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-68", name: "Pote Redondo 145ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-69", name: "Pote Redondo 250ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-70", name: "Pote Retangular 150ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-71", name: "Pote Retangular 500ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-72", name: "Embalagem Quadrada Pequena", category: "Embalagens", min: 30, unit: "un" },
  { id: "si-73", name: "Embalagem Quadrada Grande", category: "Embalagens", min: 30, unit: "un" },
  { id: "si-74", name: "Embalagem Triangular", category: "Embalagens", min: 30, unit: "un" },
  { id: "si-75", name: "Embalagem Redonda", category: "Embalagens", min: 30, unit: "un" },
  { id: "si-76", name: "Copo Tampa Bolha 250ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-77", name: "Copo Tampa Bolha 300ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-78", name: "Embalagem para Bolo Gelado", category: "Embalagens", min: 30, unit: "un" },
  { id: "si-79", name: "Forminha de Brigadeiro N2", category: "Embalagens", min: 200, unit: "un" },
  { id: "si-80", name: "Forminha de Brigadeiro N5", category: "Embalagens", min: 200, unit: "un" },
  { id: "si-81", name: "Sacola de Papelão A", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-82", name: "Sacola de Papelão B", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-83", name: "Sacola de Papelão C", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-84", name: "Caixa para Bolo 230", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-85", name: "Caixa para Bolo 250", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-86", name: "Caixa para Bolo 280", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-87", name: "Caixa para Bolo 300", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-88", name: "Caixa para Bolo 320", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-89", name: "Caixa para Bolo 350", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-90", name: "Caixa Quadrada 25 Doces", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-91", name: "Caixa Quadrada 50 Doces", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-92", name: "Caixa Quadrada 100 Doces", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-93", name: "Cake MDF 230", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-94", name: "Cake MDF 250", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-95", name: "Cake MDF 280", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-96", name: "Cake MDF 300", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-97", name: "Cake MDF 320", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-98", name: "Cake MDF 350", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-99", name: "Papel Manteiga", category: "Embalagens", min: 50, unit: "folha" },
];

export const SEED_BRANDS: { id: string; nome: string }[] = [
  { id: "br-01", nome: "União" },
  { id: "br-02", nome: "Caravela" },
  { id: "br-03", nome: "Barra" },
  { id: "br-04", nome: "Anaconda" },
  { id: "br-05", nome: "Renata" },
  { id: "br-06", nome: "Maizena" },
  { id: "br-07", nome: "Royal" },
  { id: "br-08", nome: "Liza" },
  { id: "br-09", nome: "Du Porto" },
  { id: "br-10", nome: "SoCoco" },
  { id: "br-11", nome: "DuCoco" },
  { id: "br-12", nome: "Nestlé" },
  { id: "br-13", nome: "Piracanjuba" },
  { id: "br-14", nome: "Italac" },
  { id: "br-15", nome: "Líder" },
  { id: "br-16", nome: "Parmalat" },
  { id: "br-17", nome: "Mix" },
  { id: "br-18", nome: "Arcolor" },
  { id: "br-19", nome: "Danone" },
  { id: "br-20", nome: "Qualy" },
  { id: "br-21", nome: "Garoto" },
  { id: "br-22", nome: "Melken" },
  { id: "br-23", nome: "Harald" },
  { id: "br-24", nome: "Terrinha" },
  { id: "br-25", nome: "Cisne" },
  { id: "br-26", nome: "Ferrero" },
  { id: "br-27", nome: "Tang" },
  { id: "br-28", nome: "Mago" },
  { id: "br-29", nome: "Iceberg" },
  { id: "br-30", nome: "Mavalerio" },
  { id: "br-31", nome: "Prafesta" },
  { id: "br-32", nome: "Lacta" },
  { id: "br-33", nome: "Vitarela" },
  { id: "br-34", nome: "Norcal" },
  { id: "br-35", nome: "Santa Clara" },
  { id: "br-36", nome: "Lopes" },
  { id: "br-37", nome: "Fazenda" },
];

export const SEED_LINKS: Record<string, string[]> = {
  "si-01": ["br-01", "br-02", "br-03"],
  "si-02": ["br-04", "br-05"],
  "si-03": ["br-06"],
  "si-04": ["br-07"],
  "si-05": ["br-21", "br-23"],
  "si-06": ["br-08"],
  "si-08": ["br-09"],
  "si-09": ["br-10"],
  "si-10": ["br-11"],
  "si-11": ["br-12", "br-13", "br-14"],
  "si-12": ["br-12"],
  "si-13": ["br-15", "br-13", "br-14", "br-16"],
  "si-14": ["br-13", "br-16"],
  "si-15": ["br-17", "br-18"],
  "si-16": ["br-19"],
  "si-17": ["br-20"],
  "si-18": ["br-21", "br-22"],
  "si-19": ["br-21", "br-22"],
  "si-20": ["br-12", "br-22"],
  "si-21": ["br-21", "br-22"],
  "si-22": ["br-23"],
  "si-23": ["br-23"],
  "si-25": ["br-24"],
  "si-26": ["br-35"],
  "si-28": ["br-25"],
  "si-29": ["br-26"],
  "si-30": ["br-27"],
  "si-31": ["br-27"],
  "si-32": ["br-27"],
  "si-33": ["br-27"],
  "si-34": ["br-12"],
  "si-35": ["br-17", "br-28", "br-29"],
  "si-36": ["br-28"],
  "si-37": ["br-09"],
  "si-38": ["br-36"],
  "si-39": ["br-34"],
  "si-40": ["br-37"],
  "si-41": ["br-37"],
  "si-42": ["br-37"],
  "si-43": ["br-37"],
  "si-44": ["br-37"],
  "si-45": ["br-37"],
  "si-46": ["br-37"],
  "si-47": ["br-37"],
  "si-48": ["br-37"],
  "si-49": ["br-37"],
  "si-50": ["br-37"],
  "si-51": ["br-37"],
  "si-52": ["br-37"],
  "si-53": ["br-28"],
  "si-54": ["br-30"],
  "si-55": ["br-30"],
  "si-56": ["br-30"],
  "si-57": ["br-22"],
  "si-58": ["br-30"],
  "si-59": ["br-12"],
  "si-60": ["br-26"],
  "si-61": ["br-32"],
  "si-62": ["br-32"],
  "si-63": ["br-33"],
  "si-66": ["br-31"],
  "si-68": ["br-31"],
  "si-69": ["br-31"],
  "si-70": ["br-31"],
  "si-71": ["br-31"],
  "si-72": ["br-31"],
  "si-73": ["br-31"],
  "si-74": ["br-31"],
  "si-75": ["br-31"],
  "si-76": ["br-31"],
  "si-77": ["br-31"],
  "si-78": ["br-31"],
  "si-79": ["br-31"],
  "si-80": ["br-31"],
};

/* === LOTES DE ENTRADA: [insumoId, brandId, quantidade, precoUnitario, dataEntrada?] === */
type SeedLote = [string, string, number, number, string?];

const LOTES_SEED: SeedLote[] = [
  ["si-43", "br-37", 3, 7],
  ["si-01", "br-01", 1, 4, "2026-09-05"],
  ["si-01", "br-02", 1, 3.5, "2026-09-10"],
  ["si-01", "br-03", 1, 5, "2026-09-15"],
  ["si-42", "br-37", 2, 32],
  ["si-38", "br-36", 3, 18],
  ["si-03", "br-06", 5, 14],
  ["si-15", "br-17", 100, 0.08],
  ["si-27", "", 500, 0.02],
  ["si-63", "br-33", 5, 4.5],
  ["si-41", "br-37", 2, 85],
  ["si-39", "br-34", 5, 18.5],
  ["si-18", "br-21", 5, 48],
  ["si-21", "br-21", 3, 48],
  ["si-20", "br-12", 3, 52],
  ["si-05", "br-21", 5, 38],
  ["si-60", "br-26", 5, 7.5],
  ["si-59", "br-12", 5, 3.8],
  ["si-19", "br-21", 3, 50],
  ["si-61", "br-32", 10, 1.2],
  ["si-62", "br-32", 10, 1.2],
  ["si-22", "br-23", 5, 28],
  ["si-23", "br-23", 3, 29],
  ["si-52", "br-37", 3, 6],
  ["si-09", "br-10", 5, 35],
  ["si-58", "br-30", 500, 0.03],
  ["si-55", "br-30", 500, 0.05],
  ["si-54", "br-30", 500, 0.04],
  ["si-53", "br-28", 3, 32],
  ["si-35", "br-17", 5, 8.5],
  ["si-29", "br-26", 3, 65],
  ["si-14", "br-13", 20, 3.8],
  ["si-08", "br-09", 500, 0.03],
  ["si-02", "br-04", 10, 4.5],
  ["si-04", "br-07", 250, 0.04],
  ["si-25", "br-24", 5, 5],
  ["si-26", "br-35", 5, 16],
  ["si-56", "br-30", 2, 22],
  ["si-57", "br-22", 2, 55],
  ["si-47", "br-37", 2, 22],
  ["si-48", "br-37", 3, 4.5],
  ["si-11", "br-12", 20, 6.5],
  ["si-10", "br-11", 10, 5.5],
  ["si-12", "br-12", 5, 42],
  ["si-13", "br-15", 10, 4.9],
  ["si-37", "br-09", 500, 0.03],
  ["si-45", "br-37", 3, 6],
  ["si-49", "br-37", 3, 9],
  ["si-50", "br-37", 2, 7.5],
  ["si-51", "br-37", 2, 8],
  ["si-16", "br-19", 5, 45],
  ["si-44", "br-37", 3, 12],
  ["si-17", "br-20", 5, 14],
  ["si-40", "br-37", 5, 28],
  ["si-34", "br-12", 3, 12],
  ["si-06", "br-08", 6, 7.5],
  ["si-07", "", 30, 0.65],
  ["si-99", "", 50, 0.3],
  ["si-36", "br-28", 100, 0.15],
  ["si-28", "br-25", 1000, 0.003],
  ["si-31", "br-27", 3, 1.3],
  ["si-33", "br-27", 3, 1.3],
  ["si-32", "br-27", 3, 1.3],
  ["si-30", "br-27", 5, 1.3],
  ["si-24", "", 5, 30],
  ["si-46", "br-37", 3, 15],
  ["si-84", "", 20, 4],
  ["si-85", "", 20, 4.2],
  ["si-86", "", 20, 4.5],
  ["si-87", "", 20, 4.8],
  ["si-88", "", 20, 5.2],
  ["si-89", "", 20, 5.8],
  ["si-92", "", 20, 4.5],
  ["si-90", "", 20, 2.5],
  ["si-91", "", 20, 3.2],
  ["si-93", "", 10, 3.2],
  ["si-94", "", 10, 3.5],
  ["si-95", "", 10, 3.8],
  ["si-96", "", 10, 4.2],
  ["si-97", "", 10, 4.6],
  ["si-98", "", 10, 5],
  ["si-66", "br-31", 100, 0.12],
  ["si-76", "br-31", 50, 0.85],
  ["si-77", "br-31", 50, 0.95],
  ["si-78", "br-31", 30, 0.8],
  ["si-73", "br-31", 30, 1.1],
  ["si-72", "br-31", 30, 0.85],
  ["si-75", "br-31", 30, 0.9],
  ["si-74", "br-31", 30, 0.85],
  ["si-79", "br-31", 200, 0.05],
  ["si-80", "br-31", 200, 0.04],
  ["si-68", "br-31", 50, 0.75],
  ["si-69", "br-31", 50, 0.95],
  ["si-70", "br-31", 50, 0.8],
  ["si-71", "br-31", 50, 1.3],
  ["si-81", "", 20, 2.2],
  ["si-82", "", 20, 2.5],
  ["si-83", "", 20, 2.8],
  ["si-67", "", 50, 0.15],
  ["si-65", "", 50, 0.08],
  ["si-64", "", 50, 0.1],
];

export interface SeedBatch {
  id: string;
  insumoId: string;
  brandId: string;
  dataEntrada: string;
  quantidadeInicial: number;
  quantidadeRestante: number;
  precoUnitario: number;
}

export const SEED_BATCHES: SeedBatch[] = LOTES_SEED.map(([insumoId, brandId, quantidade, precoUnitario, dataEntrada]) => ({
  id: `l-${insumoId}-${brandId || "sm"}`,
  insumoId,
  brandId,
  dataEntrada: dataEntrada ?? "2026-09-15",
  quantidadeInicial: quantidade,
  quantidadeRestante: quantidade,
  precoUnitario,
}));
