export interface SeedStockItem {
  id: string;
  name: string;
  category: string;
  min: number;
  unit: string;
}

export const SEED_STOCK: SeedStockItem[] = [
  // ── Uso Interno ──
  { id: "si-01", name: "Açúcar", category: "Uso Interno", min: 10, unit: "kg" },
  { id: "si-02", name: "Farinha de Trigo", category: "Uso Interno", min: 10, unit: "kg" },
  { id: "si-03", name: "Amido de Milho", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-04", name: "Fermento em Pó", category: "Uso Interno", min: 3, unit: "g" },
  { id: "si-05", name: "Chocolate em Pó 50%", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-06", name: "Óleo", category: "Uso Interno", min: 6, unit: "L" },
  { id: "si-07", name: "Ovos", category: "Uso Interno", min: 30, unit: "un" },
  { id: "si-08", name: "Emulsificante", category: "Uso Interno", min: 2, unit: "g" },
  { id: "si-09", name: "Coco Ralado", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-10", name: "Leite de Coco", category: "Uso Interno", min: 10, unit: "lata" },
  { id: "si-11", name: "Leite Condensado", category: "Uso Interno", min: 20, unit: "lata" },
  { id: "si-12", name: "Leite em Pó", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-13", name: "Leite Integral", category: "Uso Interno", min: 10, unit: "L" },
  { id: "si-14", name: "Creme de Leite", category: "Uso Interno", min: 20, unit: "caixa" },
  { id: "si-15", name: "Baunilha", category: "Uso Interno", min: 3, unit: "ml" },
  { id: "si-16", name: "Manteiga", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-17", name: "Margarina", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-18", name: "Chocolate Ao Leite Barra", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-19", name: "Chocolate Meio Amargo Barra", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-20", name: "Chocolate Branco Barra", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-21", name: "Chocolate Blend", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-22", name: "Cobertura ao Leite", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-23", name: "Cobertura Branco", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-24", name: "Suspiro", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-25", name: "Fubá", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-26", name: "Goiabada", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-27", name: "Bicarbonato de Sódio", category: "Uso Interno", min: 2, unit: "g" },
  { id: "si-28", name: "Sal", category: "Uso Interno", min: 3, unit: "g" },
  { id: "si-29", name: "Creme de Avelã", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-30", name: "Suco em Pó Morango", category: "Uso Interno", min: 5, unit: "pct" },
  { id: "si-31", name: "Suco em Pó Abacaxi", category: "Uso Interno", min: 3, unit: "pct" },
  { id: "si-32", name: "Suco em Pó Maracujá", category: "Uso Interno", min: 3, unit: "pct" },
  { id: "si-33", name: "Suco em Pó Limão", category: "Uso Interno", min: 3, unit: "pct" },
  { id: "si-34", name: "Nesquik", category: "Uso Interno", min: 3, unit: "pct" },
  { id: "si-35", name: "Corante em Gel", category: "Uso Interno", min: 5, unit: "un" },
  { id: "si-36", name: "Pó Pérola", category: "Uso Interno", min: 2, unit: "g" },
  { id: "si-37", name: "Liga Neutra", category: "Uso Interno", min: 3, unit: "g" },
  { id: "si-38", name: "Amendoim Moído", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-39", name: "Chantilly", category: "Uso Interno", min: 5, unit: "L" },
  { id: "si-40", name: "Morango", category: "Uso Interno", min: 5, unit: "kg" },
  { id: "si-41", name: "Cereja", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-42", name: "Ameixa", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-43", name: "Abacaxi", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-44", name: "Maracujá", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-45", name: "Limão", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-46", name: "Uva", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-47", name: "Kiwi", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-48", name: "Laranja", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-49", name: "Maçã", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-50", name: "Mamão", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-51", name: "Manga", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-52", name: "Coco Fresco", category: "Uso Interno", min: 3, unit: "un" },
  { id: "si-53", name: "Confeitos e Coberturas Diversos", category: "Uso Interno", min: 3, unit: "kg" },
  { id: "si-54", name: "Confeito Pérola", category: "Uso Interno", min: 2, unit: "g" },
  { id: "si-55", name: "Confeito Dourado", category: "Uso Interno", min: 1, unit: "g" },
  { id: "si-56", name: "Granulado Colorido", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-57", name: "Granulé ao Leite", category: "Uso Interno", min: 2, unit: "kg" },
  { id: "si-58", name: "Confeito Branco", category: "Uso Interno", min: 1, unit: "g" },
  { id: "si-59", name: "Chocolate KitKat", category: "Uso Interno", min: 5, unit: "un" },
  { id: "si-60", name: "Chocolate Kinder Bueno", category: "Uso Interno", min: 5, unit: "un" },
  { id: "si-61", name: "Chocolate Ouro Branco", category: "Uso Interno", min: 5, unit: "un" },
  { id: "si-62", name: "Chocolate Sonho de Valsa", category: "Uso Interno", min: 5, unit: "un" },
  { id: "si-63", name: "Biscoito de Maizena", category: "Uso Interno", min: 5, unit: "pct" },

  // ── Embalagens ──
  { id: "si-64", name: "Saquinho 5x24", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-65", name: "Saquinho 4x24", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-66", name: "Colher Descartável", category: "Embalagens", min: 100, unit: "un" },
  { id: "si-67", name: "Sacolinha Plástica 25x35", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-68", name: "Pote Redondo 145ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-69", name: "Pote Redondo 250ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-70", name: "Pote Retangular 150ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-71", name: "Pote Retangular 500ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-72", name: "Embalagem Quadrada Pequena", category: "Embalagens", min: 30, unit: "un" },
  { id: "si-73", name: "Embalagem Quadrada Grande", category: "Embalagens", min: 30, unit: "un" },
  { id: "si-74", name: "Embalagem Triangular", category: "Embalagens", min: 30, unit: "un" },
  { id: "si-75", name: "Embalagem Redonda", category: "Embalagens", min: 30, unit: "un" },
  { id: "si-76", name: "Copo Tampa Bolha 250ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-77", name: "Copo Tampa Bolha 300ml", category: "Embalagens", min: 50, unit: "un" },
  { id: "si-78", name: "Embalagem para Bolo Gelado", category: "Embalagens", min: 30, unit: "un" },
  { id: "si-79", name: "Forminha de Brigadeiro N2", category: "Embalagens", min: 200, unit: "un" },
  { id: "si-80", name: "Forminha de Brigadeiro N5", category: "Embalagens", min: 200, unit: "un" },
  { id: "si-81", name: "Sacola de Papelão A", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-82", name: "Sacola de Papelão B", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-83", name: "Sacola de Papelão C", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-84", name: "Caixa para Bolo 230", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-85", name: "Caixa para Bolo 250", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-86", name: "Caixa para Bolo 280", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-87", name: "Caixa para Bolo 300", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-88", name: "Caixa para Bolo 320", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-89", name: "Caixa para Bolo 350", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-90", name: "Caixa Quadrada 25 Doces", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-91", name: "Caixa Quadrada 50 Doces", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-92", name: "Caixa Quadrada 100 Doces", category: "Embalagens", min: 20, unit: "un" },
  { id: "si-93", name: "Cake MDF 230", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-94", name: "Cake MDF 250", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-95", name: "Cake MDF 280", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-96", name: "Cake MDF 300", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-97", name: "Cake MDF 320", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-98", name: "Cake MDF 350", category: "Embalagens", min: 10, unit: "un" },
  { id: "si-99", name: "Papel Manteiga", category: "Embalagens", min: 50, unit: "folha" },
];
